export const Classic = () => {
  const size = 60;
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 56 54"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect x="40" width="2" height="2" fill="currentColor" />
      <rect x="34" width="2" height="2" fill="currentColor" />
      <rect x="36" width="2" height="2" fill="currentColor" />
      <rect x="38" width="2" height="2" fill="currentColor" />
      <rect x="32" y="2" width="2" height="2" fill="currentColor" />
      <rect x="28" y="4" width="2" height="2" fill="currentColor" />
      <rect x="26" y="6" width="2" height="2" fill="currentColor" />
      <rect x="24" y="8" width="2" height="2" fill="currentColor" />
      <rect x="20" y="10" width="2" height="2" fill="currentColor" />
      <rect x="18" y="12" width="2" height="2" fill="currentColor" />
      <rect x="16" y="14" width="2" height="2" fill="currentColor" />
      <rect x="14" y="16" width="2" height="2" fill="currentColor" />
      <rect x="10" y="18" width="2" height="2" fill="currentColor" />
      <rect x="8" y="20" width="2" height="2" fill="currentColor" />
      <rect x="6" y="22" width="2" height="2" fill="currentColor" />
      <rect x="12" y="16" width="2" height="2" fill="currentColor" />
      <rect x="22" y="10" width="2" height="2" fill="currentColor" />
      <rect x="30" y="2" width="2" height="2" fill="currentColor" />
      <rect x="4" y="22" width="2" height="2" fill="currentColor" />
      <rect x="30" y="18" width="2" height="2" fill="currentColor" />
      <rect x="18" y="20" width="2" height="2" fill="currentColor" />
      <rect x="8" y="22" width="2" height="2" fill="currentColor" />
      <rect x="10" y="22" width="2" height="2" fill="currentColor" />
      <rect x="12" y="22" width="2" height="2" fill="currentColor" />
      <rect x="14" y="20" width="2" height="2" fill="currentColor" />
      <rect x="16" y="20" width="2" height="2" fill="currentColor" />
      <rect x="20" y="20" width="2" height="2" fill="currentColor" />
      <rect x="22" y="20" width="2" height="2" fill="currentColor" />
      <rect x="24" y="20" width="2" height="2" fill="currentColor" />
      <rect x="26" y="18" width="2" height="2" fill="currentColor" />
      <rect x="28" y="18" width="2" height="2" fill="currentColor" />
      <rect x="32" y="18" width="2" height="2" fill="currentColor" />
      <rect x="34" y="18" width="2" height="2" fill="currentColor" />
      <rect x="34" y="16" width="2" height="2" fill="currentColor" />
      <rect x="36" y="16" width="2" height="2" fill="currentColor" />
      <rect x="32" y="6" width="2" height="2" fill="currentColor" />
      <rect x="34" y="8" width="2" height="2" fill="currentColor" />
      <rect x="34" y="10" width="2" height="2" fill="currentColor" />
      <rect x="34" y="12" width="2" height="2" fill="currentColor" />
      <rect x="36" y="14" width="2" height="2" fill="currentColor" />
      <rect x="34" y="4" width="2" height="2" fill="currentColor" />
      <rect x="34" y="6" width="2" height="2" fill="currentColor" />
      <rect x="36" y="8" width="2" height="2" fill="currentColor" />
      <rect x="36" y="10" width="2" height="2" fill="currentColor" />
      <rect x="36" y="12" width="2" height="2" fill="currentColor" />
      <rect x="38" y="14" width="2" height="2" fill="currentColor" />
      <rect x="40" y="2" width="2" height="2" fill="currentColor" />
      <rect x="38" y="4" width="2" height="2" fill="currentColor" />
      <rect x="40" y="6" width="2" height="2" fill="currentColor" />
      <rect x="40" y="8" width="2" height="2" fill="currentColor" />
      <rect x="40" y="10" width="2" height="2" fill="currentColor" />
      <rect x="40" y="12" width="2" height="2" fill="currentColor" />
      <rect x="38" y="16" width="2" height="2" fill="currentColor" />
      <rect x="36" y="18" width="2" height="2" fill="currentColor" />
      <rect x="38" y="18" width="2" height="2" fill="currentColor" />
      <rect x="38" y="20" width="2" height="2" fill="currentColor" />
      <rect x="36" y="20" width="2" height="2" fill="currentColor" />
      <rect x="34" y="20" width="2" height="2" fill="currentColor" />
      <rect x="32" y="20" width="2" height="2" fill="currentColor" />
      <rect x="22" y="22" width="2" height="2" fill="currentColor" />
      <rect x="12" y="24" width="2" height="2" fill="currentColor" />
      <rect x="6" y="26" width="2" height="2" fill="currentColor" />
      <rect x="8" y="24" width="2" height="2" fill="currentColor" />
      <rect x="10" y="24" width="2" height="2" fill="currentColor" />
      <rect x="14" y="24" width="2" height="2" fill="currentColor" />
      <rect x="16" y="24" width="2" height="2" fill="currentColor" />
      <rect x="18" y="22" width="2" height="2" fill="currentColor" />
      <rect x="20" y="22" width="2" height="2" fill="currentColor" />
      <rect x="24" y="22" width="2" height="2" fill="currentColor" />
      <rect x="26" y="22" width="2" height="2" fill="currentColor" />
      <rect x="28" y="20" width="2" height="2" fill="currentColor" />
      <rect x="30" y="20" width="2" height="2" fill="currentColor" />
      <rect x="4" y="26" width="2" height="2" fill="currentColor" />
      <rect x="4" y="28" width="2" height="2" fill="currentColor" />
      <rect x="2" y="30" width="2" height="2" fill="currentColor" />
      <rect y="30" width="2" height="2" fill="currentColor" />
      <rect y="32" width="2" height="2" fill="currentColor" />
      <rect x="12" y="34" width="2" height="2" fill="currentColor" />
      <rect x="34" y="38" width="2" height="2" fill="currentColor" />
      <rect x="2" y="34" width="2" height="2" fill="currentColor" />
      <rect x="4" y="34" width="2" height="2" fill="currentColor" />
      <rect x="6" y="34" width="2" height="2" fill="currentColor" />
      <rect x="8" y="34" width="2" height="2" fill="currentColor" />
      <rect x="10" y="34" width="2" height="2" fill="currentColor" />
      <rect x="14" y="36" width="2" height="2" fill="currentColor" />
      <rect x="16" y="36" width="2" height="2" fill="currentColor" />
      <rect x="18" y="36" width="2" height="2" fill="currentColor" />
      <rect x="20" y="36" width="2" height="2" fill="currentColor" />
      <rect x="22" y="36" width="2" height="2" fill="currentColor" />
      <rect x="24" y="36" width="2" height="2" fill="currentColor" />
      <rect x="26" y="36" width="2" height="2" fill="currentColor" />
      <rect x="28" y="36" width="2" height="2" fill="currentColor" />
      <rect x="30" y="36" width="2" height="2" fill="currentColor" />
      <rect x="32" y="38" width="2" height="2" fill="currentColor" />
      <rect x="36" y="36" width="2" height="2" fill="currentColor" />
      <rect x="38" y="36" width="2" height="2" fill="currentColor" />
      <rect x="48" y="32" width="2" height="2" fill="currentColor" />
      <rect x="44" y="34" width="2" height="2" fill="currentColor" />
      <rect x="40" y="36" width="2" height="2" fill="currentColor" />
      <rect x="42" y="34" width="2" height="2" fill="currentColor" />
      <rect x="46" y="34" width="2" height="2" fill="currentColor" />
      <rect x="50" y="32" width="2" height="2" fill="currentColor" />
      <rect x="52" y="30" width="2" height="2" fill="currentColor" />
      <rect x="54" y="30" width="2" height="2" fill="currentColor" />
      <rect x="52" y="26" width="2" height="2" fill="currentColor" />
      <rect x="52" y="28" width="2" height="2" fill="currentColor" />
      <rect x="40" y="20" width="2" height="2" fill="currentColor" />
      <rect x="46" y="22" width="2" height="2" fill="currentColor" />
      <rect x="48" y="24" width="2" height="2" fill="currentColor" />
      <rect x="42" y="20" width="2" height="2" fill="currentColor" />
      <rect x="44" y="20" width="2" height="2" fill="currentColor" />
      <rect x="50" y="24" width="2" height="2" fill="currentColor" />
      <rect x="40" y="18" width="2" height="2" fill="currentColor" />
      <rect x="20" y="30" width="2" height="2" fill="currentColor" />
      <rect x="8" y="30" width="2" height="2" fill="currentColor" />
      <rect x="10" y="30" width="2" height="2" fill="currentColor" />
      <rect x="12" y="30" width="2" height="2" fill="currentColor" />
      <rect x="14" y="30" width="2" height="2" fill="currentColor" />
      <rect x="16" y="30" width="2" height="2" fill="currentColor" />
      <rect x="18" y="30" width="2" height="2" fill="currentColor" />
      <rect x="22" y="30" width="2" height="2" fill="currentColor" />
      <rect x="24" y="30" width="2" height="2" fill="currentColor" />
      <rect x="26" y="30" width="2" height="2" fill="currentColor" />
      <rect x="28" y="30" width="2" height="2" fill="currentColor" />
      <rect x="30" y="30" width="2" height="2" fill="currentColor" />
      <rect x="32" y="32" width="2" height="2" fill="currentColor" />
      <rect x="34" y="32" width="2" height="2" fill="currentColor" />
      <rect x="36" y="32" width="2" height="2" fill="currentColor" />
      <rect x="38" y="32" width="2" height="2" fill="currentColor" />
      <rect x="6" y="30" width="2" height="2" fill="currentColor" />
      <rect x="36" y="34" width="2" height="2" fill="currentColor" />
      <rect x="22" y="32" width="2" height="2" fill="currentColor" />
      <rect x="14" y="32" width="2" height="2" fill="currentColor" />
      <rect x="16" y="32" width="2" height="2" fill="currentColor" />
      <rect x="18" y="32" width="2" height="2" fill="currentColor" />
      <rect x="20" y="32" width="2" height="2" fill="currentColor" />
      <rect x="24" y="32" width="2" height="2" fill="currentColor" />
      <rect x="26" y="32" width="2" height="2" fill="currentColor" />
      <rect x="28" y="32" width="2" height="2" fill="currentColor" />
      <rect x="30" y="32" width="2" height="2" fill="currentColor" />
      <rect x="34" y="34" width="2" height="2" fill="currentColor" />
      <rect x="4" y="30" width="2" height="2" fill="currentColor" />
      <rect x="6" y="36" width="2" height="2" fill="currentColor" />
      <rect x="8" y="38" width="2" height="2" fill="currentColor" />
      <rect x="8" y="40" width="2" height="2" fill="currentColor" />
      <rect x="8" y="42" width="2" height="2" fill="currentColor" />
      <rect x="8" y="44" width="2" height="2" fill="currentColor" />
      <rect x="8" y="46" width="2" height="2" fill="currentColor" />
      <rect x="8" y="48" width="2" height="2" fill="currentColor" />
      <rect x="10" y="48" width="2" height="2" fill="currentColor" />
      <rect x="12" y="48" width="2" height="2" fill="currentColor" />
      <rect x="12" y="46" width="2" height="2" fill="currentColor" />
      <rect x="12" y="36" width="2" height="2" fill="currentColor" />
      <rect x="12" y="38" width="2" height="2" fill="currentColor" />
      <rect x="12" y="40" width="2" height="2" fill="currentColor" />
      <rect x="12" y="42" width="2" height="2" fill="currentColor" />
      <rect x="12" y="44" width="2" height="2" fill="currentColor" />
      <rect x="8" y="36" width="2" height="2" fill="currentColor" />
      <rect x="10" y="36" width="2" height="2" fill="currentColor" />
      <rect x="18" y="36" width="2" height="2" fill="currentColor" />
      <rect x="28" y="46" width="2" height="2" fill="currentColor" />
      <rect x="20" y="46" width="2" height="2" fill="currentColor" />
      <rect x="22" y="46" width="2" height="2" fill="currentColor" />
      <rect x="30" y="46" width="2" height="2" fill="currentColor" />
      <rect x="30" y="38" width="2" height="2" fill="currentColor" />
      <rect x="30" y="40" width="2" height="2" fill="currentColor" />
      <rect x="30" y="42" width="2" height="2" fill="currentColor" />
      <rect x="30" y="44" width="2" height="2" fill="currentColor" />
      <rect x="28" y="38" width="2" height="2" fill="currentColor" />
      <rect x="28" y="40" width="2" height="2" fill="currentColor" />
      <rect x="28" y="42" width="2" height="2" fill="currentColor" />
      <rect x="28" y="44" width="2" height="2" fill="currentColor" />
      <rect x="20" y="44" width="2" height="2" fill="currentColor" />
      <rect x="20" y="38" width="2" height="2" fill="currentColor" />
      <rect x="20" y="40" width="2" height="2" fill="currentColor" />
      <rect x="20" y="42" width="2" height="2" fill="currentColor" />
      <rect x="20" y="36" width="2" height="2" fill="currentColor" />
      <rect x="40" y="38" width="2" height="2" fill="currentColor" />
      <rect x="42" y="36" width="2" height="2" fill="currentColor" />
      <rect x="38" y="38" width="2" height="2" fill="currentColor" />
      <rect x="36" y="38" width="2" height="2" fill="currentColor" />
      <rect x="36" y="40" width="2" height="2" fill="currentColor" />
      <rect x="36" y="42" width="2" height="2" fill="currentColor" />
      <rect x="38" y="44" width="2" height="2" fill="currentColor" />
      <rect x="38" y="46" width="2" height="2" fill="currentColor" />
      <rect x="38" y="48" width="2" height="2" fill="currentColor" />
      <rect x="38" y="50" width="2" height="2" fill="currentColor" />
      <rect x="38" y="52" width="2" height="2" fill="currentColor" />
      <rect x="40" y="52" width="2" height="2" fill="currentColor" />
      <rect x="42" y="52" width="2" height="2" fill="currentColor" />
      <rect x="42" y="50" width="2" height="2" fill="currentColor" />
      <rect x="40" y="50" width="2" height="2" fill="currentColor" />
      <rect x="42" y="38" width="2" height="2" fill="currentColor" />
      <rect x="42" y="40" width="2" height="2" fill="currentColor" />
      <rect x="42" y="42" width="2" height="2" fill="currentColor" />
      <rect x="42" y="44" width="2" height="2" fill="currentColor" />
      <rect x="42" y="46" width="2" height="2" fill="currentColor" />
      <rect x="42" y="48" width="2" height="2" fill="currentColor" />
      <rect x="16" y="50" width="2" height="2" fill="currentColor" />
      <rect x="18" y="50" width="2" height="2" fill="currentColor" />
      <rect x="20" y="50" width="2" height="2" fill="currentColor" />
      <rect x="27" y="52" width="4" height="2" fill="currentColor" />
      <rect x="28" y="50" width="2" height="2" fill="currentColor" />
      <rect x="30" y="50" width="2" height="2" fill="currentColor" />
      <rect x="30" y="48" width="2" height="2" fill="currentColor" />
      <rect x="20" y="48" width="2" height="2" fill="currentColor" />
      <rect x="22" y="48" width="2" height="2" fill="currentColor" />
      <rect x="24" y="48" width="2" height="2" fill="currentColor" />
      <rect x="26" y="48" width="2" height="2" fill="currentColor" />
      <rect x="28" y="48" width="2" height="2" fill="currentColor" />
    </svg>
  );
};
