export const GENRE_CATEGORY = Object.freeze({
  "K-POP": "k-pop",
  어쿠스틱: "acoustic",
  팝: "pop",
  힙합: "hip-hop",
  "R&B": "r-n-b",
  CHILL: "chill",
  클래식: "classical",
  재즈: "jazz",
  영화: "movies",
  ROCK: "rock",
  댄스: "dance",
  애니메이션: "anime",
  어린이: "kids",
  EDM: "edm",
  블루스: "blues",
  "J-POP": "j-pop",
  인디: "indie",
  "WORK-OUT": "work-out",
});
