export const GENRE_CATEGORY = Object.freeze({
  "K-POP": ["k-pop"],
  어쿠스틱: ["acoustic", "country", "folk"],
  팝: ["pop", "pop-film", "power-pop", "synth-pop"],
  힙합: ["hip-hop"],
  "R&B": ["r-n-b"],
  CHILL: ["chill", "ambient", "rainy-day", "sleep", "study"],
  클래식: ["classical", "opera", "piano", "new-age"],
  재즈: ["jazz"],
  영화: ["movies"],
  록: ["hard-rock", "heavy-metal", "rock", "rock-n-roll", "punk-rock"],
  댄스: ["dance", "dancehall", "club", "disco", "techno", "trance"],
  애니메이션: ["anime", "disney"],
  어린이: ["children", "kids"],
  일렉트로닉: ["electro", "electronic", "edm", "dubstep"],
  블루스: ["blues"],
  "J-POP": ["j-dance", "j-idol", "j-pop", "j-rock"],
  인디: ["indie", "indie-pop"],
  "WORK-OUT": ["work-out"],
});
